_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 55
                - 103
            "3":
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
